### ISSUE TITLE
Unhandled promise rejection in src/database/mysql/mysqlDatabase.js

### ISSUE THREAD

**Issue by willdurand** [Zoapp/core#1]
I think that the db schema was not up to date, but I guess promise rejections should be handled in any case :)

```
2018-02-12T10:56:54.109Z - info: Start Opla.ai 0.9.0
(node:25089) UnhandledPromiseRejectionWarning: Error: Table 'opla_backend_dev.middlewares' doesn't exist in engine
    at PromiseConnection.query (/Users/william/projects/opla/opla-backend-pro/node_modules/mysql2/promise.js:89:20)
    at MySQLDatabase.query (/Users/william/projects/opla/opla-backend-pro/node_modules/src/database/mysql/mysqlDatabase.js:233:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:25089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mikbry** [comment]
Mysql2 module seems to not handle correctly some promise errors. Especially timeout or socket breaks.

**Comment by willdurand** [comment]
it seems the error handling is not entirely done, when using `async/await` we should always have `try/catch` blocks.

**Comment by mikbry** [comment]
In Zoauth, ZoauthRouter line 71, I put a global try catch to handle errors. But it seems not enough...
